#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.6.0.
//
// This code was generated with the following options:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'padlen': 1,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'verbosity': 30}


#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>

// Code for element element_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1






ufcx_finite_element element_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1 =
{
  .signature = "Basix element (P, quadrilateral, 1, gll_warped, unset, False)",
  .cell_shape = quadrilateral,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 4,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 4,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1

// Code for element element_547176877e4405a4f795e23a410bc677fb590bfe

int value_shape_element_547176877e4405a4f795e23a410bc677fb590bfe[1] = { 2 };
int reference_value_shape_element_547176877e4405a4f795e23a410bc677fb590bfe[1] = { 2 };
ufcx_finite_element* sub_elements_element_547176877e4405a4f795e23a410bc677fb590bfe[2] = { &element_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1, &element_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1 };


ufcx_finite_element element_547176877e4405a4f795e23a410bc677fb590bfe =
{
  .signature = "VectorElement(Basix element (P, quadrilateral, 1, gll_warped, unset, False), 2)",
  .cell_shape = quadrilateral,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 8,
  .value_rank = 1,
  .value_shape = value_shape_element_547176877e4405a4f795e23a410bc677fb590bfe,
  .value_size = 2,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_547176877e4405a4f795e23a410bc677fb590bfe,
  .reference_value_size = 2,
  .degree = 1,
  .block_size = 2,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 4,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 2,
  .sub_elements = sub_elements_element_547176877e4405a4f795e23a410bc677fb590bfe,
  .custom_element = NULL
};

// End of code for element element_547176877e4405a4f795e23a410bc677fb590bfe

// Code for element element_273bb6edb683274804fdc4c271d881cf56dcbd3d






ufcx_finite_element element_273bb6edb683274804fdc4c271d881cf56dcbd3d =
{
  .signature = "Basix element (P, quadrilateral, 2, gll_warped, unset, False)",
  .cell_shape = quadrilateral,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 9,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 2,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 4,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_273bb6edb683274804fdc4c271d881cf56dcbd3d

// Code for dofmap dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1



void tabulate_entity_dofs_dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 2:
    dofs[0] = 1;
    dofs[1] = 3;
    break;
  case 3:
    dofs[0] = 2;
    dofs[1] = 3;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1[4] = { 1, 2, 4, 0 };

ufcx_dofmap dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1 =
{
  .signature = "FFCx dofmap for Basix element (P, quadrilateral, 1, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1

// Code for dofmap dofmap_547176877e4405a4f795e23a410bc677fb590bfe

ufcx_dofmap* sub_dofmaps_dofmap_547176877e4405a4f795e23a410bc677fb590bfe[2] = { &dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1, &dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1 };

void tabulate_entity_dofs_dofmap_547176877e4405a4f795e23a410bc677fb590bfe(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_547176877e4405a4f795e23a410bc677fb590bfe(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    break;
  case 2:
    dofs[0] = 1;
    dofs[1] = 3;
    break;
  case 3:
    dofs[0] = 2;
    dofs[1] = 3;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_547176877e4405a4f795e23a410bc677fb590bfe[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_547176877e4405a4f795e23a410bc677fb590bfe[4] = { 1, 2, 4, 0 };

ufcx_dofmap dofmap_547176877e4405a4f795e23a410bc677fb590bfe =
{
  .signature = "FFCx dofmap for VectorElement(Basix element (P, quadrilateral, 1, gll_warped, unset, False), 2)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 2,
  .num_entity_dofs = num_entity_dofs_dofmap_547176877e4405a4f795e23a410bc677fb590bfe,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_547176877e4405a4f795e23a410bc677fb590bfe,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_547176877e4405a4f795e23a410bc677fb590bfe,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_547176877e4405a4f795e23a410bc677fb590bfe,
  .num_sub_dofmaps = 2,
  .sub_dofmaps = sub_dofmaps_dofmap_547176877e4405a4f795e23a410bc677fb590bfe
};

// End of code for dofmap dofmap_547176877e4405a4f795e23a410bc677fb590bfe

// Code for dofmap dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d



void tabulate_entity_dofs_dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 4;
    break;
  case 1:
    dofs[0] = 5;
    break;
  case 2:
    dofs[0] = 6;
    break;
  case 3:
    dofs[0] = 7;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 8;
    break;
  }
  break;
}
}

void tabulate_entity_closure_dofs_dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    break;
  case 1:
    dofs[0] = 1;
    break;
  case 2:
    dofs[0] = 2;
    break;
  case 3:
    dofs[0] = 3;
    break;
  }
  break;
case 1:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 4;
    break;
  case 1:
    dofs[0] = 0;
    dofs[1] = 2;
    dofs[2] = 5;
    break;
  case 2:
    dofs[0] = 1;
    dofs[1] = 3;
    dofs[2] = 6;
    break;
  case 3:
    dofs[0] = 2;
    dofs[1] = 3;
    dofs[2] = 7;
    break;
  }
  break;
case 2:
  switch (i)
  {
  case 0:
    dofs[0] = 0;
    dofs[1] = 1;
    dofs[2] = 2;
    dofs[3] = 3;
    dofs[4] = 4;
    dofs[5] = 5;
    dofs[6] = 6;
    dofs[7] = 7;
    dofs[8] = 8;
    break;
  }
  break;
}
}

int num_entity_dofs_dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d[4] = { 1, 1, 1, 0 };

int num_entity_closure_dofs_dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d[4] = { 1, 3, 9, 0 };

ufcx_dofmap dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d =
{
  .signature = "FFCx dofmap for Basix element (P, quadrilateral, 2, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 9,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d

// Code for integral integral_0e9d1cbd6a82dbca0f8b5d515aed78c5bf974453

void tabulate_tensor_integral_0e9d1cbd6a82dbca0f8b5d515aed78c5bf974453(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
  // Quadrature rules
  static const double weights_618[36] = { 0.007338020422245067, 0.0154518233430958, 0.02004127932945162, 0.02004127932945161, 0.0154518233430958, 0.007338020422245067, 0.0154518233430958, 0.03253722814704186, 0.04220134177189697, 0.04220134177189695, 0.03253722814704186, 0.0154518233430958, 0.02004127932945162, 0.04220134177189697, 0.0547358625418242, 0.05473586254182417, 0.04220134177189697, 0.02004127932945162, 0.02004127932945161, 0.04220134177189695, 0.05473586254182417, 0.05473586254182414, 0.04220134177189695, 0.02004127932945161, 0.0154518233430958, 0.03253722814704186, 0.04220134177189697, 0.04220134177189695, 0.03253722814704186, 0.0154518233430958, 0.007338020422245067, 0.0154518233430958, 0.02004127932945162, 0.02004127932945161, 0.0154518233430958, 0.007338020422245067 };
  // Precomputed values of basis functions and precomputations
  // FE* dimensions: [permutation][entities][points][dofs]
  static const double FE3_C0_Q618[1][1][36][4] =
    { { { { 0.9336096058311416, 0.03262515127043442, 0.03262515127043442, 0.001140091627989614 },
          { 0.8025591240135448, 0.02804556921958767, 0.1636756330880313, 0.005719673678836357 },
          { 0.5983984542032248, 0.02091113883837369, 0.3678363028983512, 0.01285410406005031 },
          { 0.3678363028983512, 0.01285410406005029, 0.5983984542032248, 0.02091113883837366 },
          { 0.1636756330880313, 0.005719673678836273, 0.8025591240135448, 0.02804556921958762 },
          { 0.03262515127043442, 0.001140091627989559, 0.9336096058311416, 0.03262515127043436 },
          { 0.8025591240135448, 0.1636756330880313, 0.02804556921958767, 0.005719673678836357 },
          { 0.6899041564209059, 0.1407005368122265, 0.1407005368122265, 0.02869476995464121 },
          { 0.5144014545446529, 0.1049081384969456, 0.3162032386884794, 0.06448716826992212 },
          { 0.3162032386884794, 0.0644871682699221, 0.5144014545446529, 0.1049081384969455 },
          { 0.1407005368122264, 0.02869476995464115, 0.6899041564209059, 0.1407005368122264 },
          { 0.02804556921958767, 0.005719673678836301, 0.8025591240135448, 0.1636756330880313 },
          { 0.5983984542032248, 0.3678363028983512, 0.02091113883837369, 0.0128541040600503 },
          { 0.5144014545446529, 0.3162032386884794, 0.1049081384969456, 0.06448716826992211 },
          { 0.3835443720333503, 0.2357652210082481, 0.2357652210082481, 0.1449251859501534 },
          { 0.2357652210082481, 0.1449251859501534, 0.3835443720333503, 0.2357652210082481 },
          { 0.1049081384969455, 0.06448716826992207, 0.5144014545446529, 0.3162032386884794 },
          { 0.02091113883837369, 0.01285410406005028, 0.5983984542032248, 0.3678363028983512 },
          { 0.3678363028983512, 0.5983984542032248, 0.01285410406005028, 0.02091113883837366 },
          { 0.3162032386884794, 0.5144014545446529, 0.0644871682699221, 0.1049081384969455 },
          { 0.2357652210082481, 0.3835443720333503, 0.1449251859501534, 0.2357652210082481 },
          { 0.1449251859501534, 0.2357652210082481, 0.2357652210082481, 0.3835443720333503 },
          { 0.06448716826992207, 0.1049081384969455, 0.3162032386884794, 0.5144014545446529 },
          { 0.01285410406005028, 0.02091113883837369, 0.3678363028983512, 0.5983984542032248 },
          { 0.1636756330880313, 0.8025591240135448, 0.005719673678836273, 0.02804556921958765 },
          { 0.1407005368122264, 0.6899041564209059, 0.02869476995464115, 0.1407005368122264 },
          { 0.1049081384969455, 0.514401454544653, 0.06448716826992208, 0.3162032386884794 },
          { 0.06448716826992208, 0.3162032386884794, 0.1049081384969455, 0.514401454544653 },
          { 0.02869476995464113, 0.1407005368122265, 0.1407005368122264, 0.689904156420906 },
          { 0.005719673678836273, 0.0280455692195877, 0.1636756330880313, 0.8025591240135448 },
          { 0.03262515127043442, 0.9336096058311416, 0.001140091627989559, 0.03262515127043436 },
          { 0.02804556921958767, 0.8025591240135448, 0.005719673678836301, 0.1636756330880313 },
          { 0.02091113883837369, 0.5983984542032248, 0.01285410406005029, 0.3678363028983512 },
          { 0.01285410406005029, 0.3678363028983512, 0.02091113883837369, 0.5983984542032248 },
          { 0.005719673678836273, 0.1636756330880313, 0.02804556921958767, 0.8025591240135448 },
          { 0.001140091627989559, 0.03262515127043442, 0.03262515127043442, 0.9336096058311416 } } } };
  static const double FE4_C0_D10_Q618[1][1][36][4] =
    { { { { -0.9662347571015759, 0.9662347571015759, -0.03376524289842403, 0.03376524289842386 },
          { -0.8306046932331322, 0.8306046932331322, -0.1693953067668678, 0.1693953067668676 },
          { -0.6193095930415985, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015 },
          { -0.3806904069584015, 0.3806904069584015, -0.6193095930415985, 0.6193095930415985 },
          { -0.1693953067668676, 0.1693953067668676, -0.8306046932331324, 0.8306046932331325 },
          { -0.03376524289842403, 0.03376524289842403, -0.9662347571015759, 0.9662347571015761 },
          { -0.9662347571015759, 0.9662347571015759, -0.03376524289842403, 0.03376524289842386 },
          { -0.8306046932331322, 0.8306046932331322, -0.1693953067668678, 0.1693953067668676 },
          { -0.6193095930415985, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015 },
          { -0.3806904069584015, 0.3806904069584015, -0.6193095930415985, 0.6193095930415985 },
          { -0.1693953067668676, 0.1693953067668676, -0.8306046932331324, 0.8306046932331325 },
          { -0.03376524289842403, 0.03376524289842403, -0.9662347571015759, 0.9662347571015761 },
          { -0.9662347571015759, 0.9662347571015759, -0.03376524289842403, 0.03376524289842386 },
          { -0.8306046932331322, 0.8306046932331322, -0.1693953067668678, 0.1693953067668676 },
          { -0.6193095930415985, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015 },
          { -0.3806904069584015, 0.3806904069584015, -0.6193095930415985, 0.6193095930415985 },
          { -0.1693953067668676, 0.1693953067668676, -0.8306046932331324, 0.8306046932331325 },
          { -0.03376524289842403, 0.03376524289842403, -0.9662347571015759, 0.9662347571015761 },
          { -0.9662347571015759, 0.9662347571015759, -0.03376524289842403, 0.03376524289842386 },
          { -0.8306046932331322, 0.8306046932331322, -0.1693953067668678, 0.1693953067668676 },
          { -0.6193095930415985, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015 },
          { -0.3806904069584015, 0.3806904069584015, -0.6193095930415985, 0.6193095930415985 },
          { -0.1693953067668676, 0.1693953067668676, -0.8306046932331324, 0.8306046932331325 },
          { -0.03376524289842403, 0.03376524289842403, -0.9662347571015759, 0.9662347571015761 },
          { -0.9662347571015759, 0.9662347571015759, -0.03376524289842403, 0.03376524289842386 },
          { -0.8306046932331322, 0.8306046932331322, -0.1693953067668678, 0.1693953067668676 },
          { -0.6193095930415985, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015 },
          { -0.3806904069584015, 0.3806904069584015, -0.6193095930415985, 0.6193095930415985 },
          { -0.1693953067668676, 0.1693953067668676, -0.8306046932331324, 0.8306046932331325 },
          { -0.03376524289842403, 0.03376524289842403, -0.9662347571015759, 0.9662347571015761 },
          { -0.9662347571015759, 0.9662347571015759, -0.03376524289842403, 0.03376524289842386 },
          { -0.8306046932331322, 0.8306046932331322, -0.1693953067668678, 0.1693953067668676 },
          { -0.6193095930415985, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015 },
          { -0.3806904069584015, 0.3806904069584015, -0.6193095930415985, 0.6193095930415985 },
          { -0.1693953067668676, 0.1693953067668676, -0.8306046932331324, 0.8306046932331325 },
          { -0.03376524289842403, 0.03376524289842403, -0.9662347571015759, 0.9662347571015761 } } } };
  static const double FE4_C1_D01_Q618[1][1][36][4] =
    { { { { -0.9662347571015759, -0.03376524289842403, 0.9662347571015759, 0.03376524289842386 },
          { -0.9662347571015759, -0.03376524289842403, 0.9662347571015759, 0.03376524289842386 },
          { -0.9662347571015759, -0.03376524289842403, 0.9662347571015759, 0.03376524289842386 },
          { -0.9662347571015759, -0.03376524289842403, 0.9662347571015759, 0.03376524289842386 },
          { -0.9662347571015759, -0.03376524289842403, 0.9662347571015759, 0.03376524289842386 },
          { -0.9662347571015759, -0.03376524289842403, 0.9662347571015759, 0.03376524289842386 },
          { -0.8306046932331322, -0.1693953067668678, 0.8306046932331322, 0.1693953067668676 },
          { -0.8306046932331322, -0.1693953067668678, 0.8306046932331322, 0.1693953067668676 },
          { -0.8306046932331322, -0.1693953067668678, 0.8306046932331322, 0.1693953067668676 },
          { -0.8306046932331322, -0.1693953067668678, 0.8306046932331322, 0.1693953067668676 },
          { -0.8306046932331322, -0.1693953067668678, 0.8306046932331322, 0.1693953067668676 },
          { -0.8306046932331322, -0.1693953067668678, 0.8306046932331322, 0.1693953067668676 },
          { -0.6193095930415985, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015 },
          { -0.6193095930415985, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015 },
          { -0.6193095930415985, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015 },
          { -0.6193095930415985, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015 },
          { -0.6193095930415985, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015 },
          { -0.6193095930415985, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015 },
          { -0.3806904069584015, -0.6193095930415985, 0.3806904069584015, 0.6193095930415985 },
          { -0.3806904069584015, -0.6193095930415985, 0.3806904069584015, 0.6193095930415985 },
          { -0.3806904069584015, -0.6193095930415985, 0.3806904069584015, 0.6193095930415985 },
          { -0.3806904069584015, -0.6193095930415985, 0.3806904069584015, 0.6193095930415985 },
          { -0.3806904069584015, -0.6193095930415985, 0.3806904069584015, 0.6193095930415985 },
          { -0.3806904069584015, -0.6193095930415985, 0.3806904069584015, 0.6193095930415985 },
          { -0.1693953067668676, -0.8306046932331324, 0.1693953067668676, 0.8306046932331325 },
          { -0.1693953067668676, -0.8306046932331324, 0.1693953067668676, 0.8306046932331325 },
          { -0.1693953067668676, -0.8306046932331324, 0.1693953067668676, 0.8306046932331325 },
          { -0.1693953067668676, -0.8306046932331324, 0.1693953067668676, 0.8306046932331325 },
          { -0.1693953067668676, -0.8306046932331324, 0.1693953067668676, 0.8306046932331325 },
          { -0.1693953067668676, -0.8306046932331324, 0.1693953067668676, 0.8306046932331325 },
          { -0.03376524289842403, -0.9662347571015759, 0.03376524289842403, 0.9662347571015761 },
          { -0.03376524289842403, -0.9662347571015759, 0.03376524289842403, 0.9662347571015761 },
          { -0.03376524289842403, -0.9662347571015759, 0.03376524289842403, 0.9662347571015761 },
          { -0.03376524289842403, -0.9662347571015759, 0.03376524289842403, 0.9662347571015761 },
          { -0.03376524289842403, -0.9662347571015759, 0.03376524289842403, 0.9662347571015761 },
          { -0.03376524289842403, -0.9662347571015759, 0.03376524289842403, 0.9662347571015761 } } } };
  static const double FE8_C0_D01_Q618[1][1][36][9] =
    { { { { -2.581265527858337, 0.09020277618134054, -0.7792966187369215, 0.02723265689645071, -0.373876276729308, 3.360562146595259, -0.1174354330777909, -0.1128750665658331, 0.4867513432951407 },
          { -2.092463211392162, 0.07312149358051434, -0.2904943022707472, 0.01015137429562457, -0.3030770551208815, 2.38295751366291, -0.08327286787613841, -0.04207584495740646, 0.3451529000782876 },
          { -1.330968809002486, 0.04651093825376718, 0.471000100118929, -0.01645918103112257, -0.1927805014176755, 0.8599687088835568, -0.03005175722264436, 0.06822070874579972, 0.1245597926718758 },
          { -0.4710001001189289, 0.01645918103112259, 1.330968809002486, -0.04651093825376709, -0.06822070874579983, -0.8599687088835568, 0.03005175722264442, 0.1927805014176756, -0.1245597926718756 },
          { 0.2904943022707476, -0.01015137429562474, 2.092463211392162, -0.0731214935805144, 0.04207584495740635, -2.38295751366291, 0.08327286787613863, 0.3030770551208818, -0.3451529000782878 },
          { 0.7792966187369219, -0.02723265689645082, 2.581265527858336, -0.09020277618134043, 0.1128750665658327, -3.360562146595259, 0.1174354330777909, 0.3738762767293085, -0.4867513432951407 },
          { -1.573434884358915, 0.3208896928768734, -0.4750276451415563, 0.09687815916170285, -1.612393836924263, 2.048462529500472, -0.417767852038576, -0.4867895424264508, 2.099183379350713 },
          { -1.275480796341693, 0.2601242956267601, -0.1770735571243339, 0.03611276191158962, -1.307062272217597, 1.452554353466027, -0.2962370575383496, -0.1814579777197851, 1.488520249937382 },
          { -0.8113046610186171, 0.1654592167059479, 0.2871025781987417, -0.05855231700922258, -0.8313929278537251, 0.5242020828198751, -0.1069068996967252, 0.2942113666440868, 0.5371815612096381 },
          { -0.2871025781987417, 0.05855231700922255, 0.8113046610186169, -0.1654592167059478, -0.2942113666440869, -0.5242020828198751, 0.1069068996967252, 0.831392927853725, -0.5371815612096379 },
          { 0.177073557124334, -0.03611276191158973, 1.275480796341693, -0.2601242956267601, 0.1814579777197851, -1.452554353466027, 0.2962370575383496, 1.307062272217597, -1.488520249937382 },
          { 0.4750276451415566, -0.09687815916170302, 1.573434884358915, -0.3208896928768732, 0.4867895424264507, -2.048462529500472, 0.417767852038576, 1.612393836924263, -2.099183379350713 },
          { -0.4233782573565651, 0.2602511617797326, -0.1278199553063604, 0.07857109166354295, -2.701811932829473, 0.5511982126629249, -0.3388222534432757, -0.8156901647634871, 3.517502097592959 },
          { -0.3432050745887292, 0.2109686027527684, -0.04764677253852442, 0.02928853263657871, -2.190182301096569, 0.390851847127253, -0.2402571353893472, -0.3040605330305838, 2.494242834127152 },
          { -0.2183050325004539, 0.1341923855167581, 0.07725326954975072, -0.04748768459943151, -1.393125725182699, 0.1410517629507029, -0.0867047009173266, 0.4929960428832867, 0.9001296822994117 },
          { -0.07725326954975076, 0.04748768459943144, 0.2183050325004537, -0.1341923855167581, -0.4929960428832866, -0.1410517629507028, 0.08670470091732665, 1.393125725182699, -0.9001296822994115 },
          { 0.04764677253852451, -0.02928853263657891, 0.3432050745887287, -0.2109686027527684, 0.3040605330305841, -0.3908518471272529, 0.2402571353893473, 2.190182301096569, -2.494242834127153 },
          { 0.1278199553063605, -0.07857109166354312, 0.4233782573565647, -0.2602511617797325, 0.8156901647634873, -0.5511982126629249, 0.3388222534432757, 2.701811932829473, -3.517502097592959 },
          { 0.2602511617797325, -0.4233782573565649, 0.0785710916635429, -0.1278199553063605, -2.701811932829473, -0.3388222534432761, 0.5511982126629251, -0.8156901647634871, 3.517502097592959 },
          { 0.2109686027527682, -0.343205074588729, 0.02928853263657868, -0.04764677253852445, -2.190182301096569, -0.2402571353893475, 0.3908518471272532, -0.3040605330305838, 2.494242834127152 },
          { 0.1341923855167579, -0.2183050325004537, -0.04748768459943152, 0.0772532695497507, -1.393125725182699, -0.08670470091732671, 0.141051762950703, 0.4929960428832867, 0.9001296822994117 },
          { 0.0474876845994314, -0.07725326954975074, -0.1341923855167581, 0.2183050325004537, -0.4929960428832866, 0.08670470091732677, -0.1410517629507029, 1.393125725182699, -0.9001296822994115 },
          { -0.02928853263657888, 0.04764677253852442, -0.2109686027527683, 0.3432050745887288, 0.3040605330305841, 0.2402571353893476, -0.3908518471272531, 2.190182301096569, -2.494242834127153 },
          { -0.07857109166354306, 0.1278199553063605, -0.2602511617797325, 0.4233782573565649, 0.8156901647634873, 0.3388222534432761, -0.5511982126629251, 2.701811932829473, -3.517502097592959 },
          { 0.3208896928768734, -1.573434884358916, 0.09687815916170256, -0.4750276451415565, -1.612393836924262, -0.4177678520385761, 2.048462529500472, -0.4867895424264507, 2.099183379350712 },
          { 0.2601242956267601, -1.275480796341693, 0.03611276191158938, -0.1770735571243339, -1.307062272217597, -0.2962370575383497, 1.452554353466027, -0.181457977719785, 1.488520249937381 },
          { 0.1654592167059478, -0.811304661018617, -0.05855231700922268, 0.2871025781987419, -0.8313929278537249, -0.1069068996967252, 0.5242020828198752, 0.2942113666440868, 0.537181561209638 },
          { 0.05855231700922253, -0.2871025781987417, -0.1654592167059478, 0.8113046610186169, -0.2942113666440869, 0.1069068996967253, -0.5242020828198752, 0.8313929278537248, -0.5371815612096378 },
          { -0.03611276191158981, 0.1770735571243341, -0.2601242956267599, 1.275480796341693, 0.1814579777197849, 0.2962370575383497, -1.452554353466027, 1.307062272217597, -1.488520249937381 },
          { -0.09687815916170306, 0.4750276451415568, -0.320889692876873, 1.573434884358916, 0.4867895424264505, 0.4177678520385761, -2.048462529500472, 1.612393836924262, -2.099183379350712 },
          { 0.09020277618134054, -2.581265527858336, 0.0272326568964506, -0.7792966187369217, -0.373876276729308, -0.1174354330777907, 3.360562146595258, -0.1128750665658331, 0.4867513432951407 },
          { 0.07312149358051434, -2.092463211392162, 0.01015137429562457, -0.2904943022707472, -0.3030770551208815, -0.08327286787613841, 2.382957513662909, -0.04207584495740646, 0.345152900078288 },
          { 0.04651093825376698, -1.330968809002485, -0.01645918103112254, 0.4710001001189289, -0.1927805014176755, -0.03005175722264436, 0.8599687088835566, 0.06822070874579972, 0.1245597926718758 },
          { 0.01645918103112234, -0.4710001001189286, -0.04651093825376684, 1.330968809002485, -0.06822070874579983, 0.03005175722264436, -0.8599687088835566, 0.1927805014176756, -0.1245597926718756 },
          { -0.01015137429562507, 0.2904943022707477, -0.07312149358051395, 2.092463211392162, 0.04207584495740613, 0.08327286787613852, -2.382957513662909, 0.3030770551208818, -0.3451529000782882 },
          { -0.02723265689645127, 0.7792966187369221, -0.09020277618133987, 2.581265527858336, 0.1128750665658327, 0.1174354330777907, -3.360562146595258, 0.3738762767293085, -0.4867513432951407 } } } };
  static const double FE8_C0_D10_Q618[1][1][36][9] =
    { { { { -2.581265527858336, -0.7792966187369215, 0.09020277618134054, 0.02723265689645094, 3.360562146595259, -0.373876276729308, -0.1128750665658331, -0.1174354330777909, 0.4867513432951407 },
          { -1.573434884358915, -0.4750276451415565, 0.3208896928768733, 0.09687815916170278, 2.048462529500472, -1.612393836924263, -0.4867895424264507, -0.4177678520385758, 2.099183379350712 },
          { -0.423378257356565, -0.1278199553063605, 0.2602511617797326, 0.07857109166354298, 0.5511982126629249, -2.701811932829473, -0.8156901647634871, -0.3388222534432757, 3.517502097592959 },
          { 0.2602511617797325, 0.07857109166354284, -0.4233782573565649, -0.1278199553063605, -0.3388222534432761, -2.701811932829473, -0.8156901647634871, 0.5511982126629251, 3.517502097592959 },
          { 0.3208896928768733, 0.0968781591617025, -1.573434884358916, -0.4750276451415565, -0.4177678520385761, -1.612393836924262, -0.4867895424264507, 2.048462529500472, 2.099183379350712 },
          { 0.09020277618134043, 0.02723265689645049, -2.581265527858336, -0.7792966187369217, -0.1174354330777907, -0.373876276729308, -0.1128750665658331, 3.360562146595258, 0.4867513432951407 },
          { -2.092463211392162, -0.2904943022707471, 0.0731214935805144, 0.01015137429562468, 2.382957513662909, -0.3030770551208816, -0.04207584495740657, -0.08327286787613852, 0.3451529000782878 },
          { -1.275480796341693, -0.1770735571243339, 0.2601242956267601, 0.03611276191158967, 1.452554353466027, -1.307062272217597, -0.181457977719785, -0.2962370575383496, 1.488520249937381 },
          { -0.3432050745887288, -0.04764677253852448, 0.2109686027527684, 0.02928853263657877, 0.390851847127253, -2.190182301096569, -0.3040605330305838, -0.2402571353893472, 2.494242834127152 },
          { 0.2109686027527683, 0.02928853263657868, -0.3432050745887288, -0.04764677253852448, -0.2402571353893475, -2.190182301096569, -0.3040605330305838, 0.3908518471272532, 2.494242834127152 },
          { 0.2601242956267601, 0.03611276191158944, -1.275480796341693, -0.177073557124334, -0.2962370575383498, -1.307062272217597, -0.181457977719785, 1.452554353466027, 1.488520249937381 },
          { 0.07312149358051417, 0.01015137429562457, -2.092463211392162, -0.2904943022707472, -0.08327286787613852, -0.3030770551208816, -0.04207584495740657, 2.382957513662909, 0.3451529000782882 },
          { -1.330968809002485, 0.4710001001189291, 0.04651093825376709, -0.01645918103112257, 0.8599687088835566, -0.1927805014176755, 0.06822070874579966, -0.0300517572226443, 0.1245597926718758 },
          { -0.8113046610186169, 0.2871025781987417, 0.1654592167059479, -0.05855231700922256, 0.5242020828198752, -0.8313929278537251, 0.2942113666440868, -0.1069068996967252, 0.5371815612096381 },
          { -0.2183050325004537, 0.07725326954975069, 0.1341923855167581, -0.04748768459943151, 0.1410517629507029, -1.393125725182699, 0.4929960428832867, -0.08670470091732659, 0.9001296822994117 },
          { 0.1341923855167581, -0.04748768459943155, -0.2183050325004537, 0.0772532695497507, -0.08670470091732668, -1.393125725182699, 0.4929960428832867, 0.1410517629507029, 0.9001296822994117 },
          { 0.1654592167059478, -0.0585523170092227, -0.8113046610186171, 0.2871025781987419, -0.1069068996967252, -0.8313929278537249, 0.2942113666440867, 0.5242020828198752, 0.537181561209638 },
          { 0.0465109382537669, -0.01645918103112259, -1.330968809002486, 0.4710001001189289, -0.0300517572226443, -0.1927805014176755, 0.06822070874579966, 0.8599687088835565, 0.1245597926718758 },
          { -0.4710001001189291, 1.330968809002486, 0.01645918103112262, -0.04651093825376704, -0.8599687088835566, -0.06822070874579983, 0.1927805014176757, 0.0300517572226443, -0.1245597926718758 },
          { -0.2871025781987417, 0.811304661018617, 0.05855231700922259, -0.1654592167059478, -0.5242020828198751, -0.2942113666440869, 0.831392927853725, 0.1069068996967252, -0.5371815612096379 },
          { -0.07725326954975073, 0.2183050325004537, 0.04748768459943147, -0.1341923855167581, -0.1410517629507028, -0.4929960428832866, 1.393125725182699, 0.08670470091732664, -0.9001296822994115 },
          { 0.04748768459943147, -0.1341923855167581, -0.07725326954975069, 0.2183050325004537, 0.08670470091732674, -0.4929960428832866, 1.393125725182699, -0.1410517629507029, -0.9001296822994115 },
          { 0.05855231700922255, -0.1654592167059478, -0.2871025781987417, 0.8113046610186169, 0.1069068996967253, -0.2942113666440868, 0.8313929278537249, -0.5242020828198752, -0.5371815612096378 },
          { 0.01645918103112236, -0.04651093825376679, -0.4710001001189287, 1.330968809002485, 0.0300517572226443, -0.06822070874579983, 0.1927805014176757, -0.8599687088835565, -0.1245597926718758 },
          { 0.2904943022707472, 2.092463211392162, -0.01015137429562474, -0.07312149358051434, -2.38295751366291, 0.04207584495740624, 0.3030770551208818, 0.08327286787613863, -0.3451529000782878 },
          { 0.1770735571243341, 1.275480796341693, -0.03611276191158976, -0.2601242956267601, -1.452554353466027, 0.1814579777197849, 1.307062272217597, 0.2962370575383497, -1.488520249937382 },
          { 0.04764677253852448, 0.3432050745887288, -0.02928853263657888, -0.2109686027527684, -0.3908518471272529, 0.3040605330305842, 2.190182301096569, 0.2402571353893473, -2.494242834127153 },
          { -0.02928853263657877, -0.2109686027527683, 0.04764677253852448, 0.3432050745887288, 0.2402571353893476, 0.3040605330305842, 2.190182301096569, -0.3908518471272531, -2.494242834127153 },
          { -0.03611276191158973, -0.2601242956267598, 0.1770735571243342, 1.275480796341693, 0.2962370575383497, 0.1814579777197849, 1.307062272217597, -1.452554353466027, -1.488520249937381 },
          { -0.01015137429562496, -0.07312149358051384, 0.2904943022707477, 2.092463211392162, 0.08327286787613852, 0.04207584495740624, 0.3030770551208818, -2.382957513662909, -0.3451529000782882 },
          { 0.7792966187369217, 2.581265527858336, -0.02723265689645082, -0.09020277618134043, -3.360562146595259, 0.1128750665658327, 0.3738762767293085, 0.1174354330777909, -0.4867513432951407 },
          { 0.4750276451415565, 1.573434884358915, -0.09687815916170285, -0.3208896928768732, -2.048462529500472, 0.4867895424264505, 1.612393836924263, 0.4177678520385758, -2.099183379350712 },
          { 0.1278199553063605, 0.4233782573565649, -0.07857109166354301, -0.2602511617797326, -0.5511982126629249, 0.8156901647634873, 2.701811932829473, 0.3388222534432757, -3.517502097592959 },
          { -0.07857109166354304, -0.2602511617797324, 0.1278199553063605, 0.4233782573565648, 0.3388222534432761, 0.8156901647634873, 2.701811932829473, -0.5511982126629251, -3.517502097592959 },
          { -0.09687815916170292, -0.320889692876873, 0.4750276451415569, 1.573434884358915, 0.4177678520385761, 0.4867895424264505, 1.612393836924262, -2.048462529500472, -2.099183379350712 },
          { -0.02723265689645116, -0.09020277618133987, 0.7792966187369221, 2.581265527858336, 0.1174354330777907, 0.1128750665658327, 0.3738762767293085, -3.360562146595258, -0.4867513432951407 } } } };
  for (int iq = 0; iq < 36; ++iq)
  {
    // Quadrature loop body setup for quadrature rule 618
    // Varying computations for quadrature rule 618
    double J_c0 = 0.0;
    double J_c3 = 0.0;
    double J_c1 = 0.0;
    double J_c2 = 0.0;
    double w0 = 0.0;
    double w1 = 0.0;
    for (int ic = 0; ic < 4; ++ic)
    {
      J_c0 += coordinate_dofs[ic * 3] * FE4_C0_D10_Q618[0][0][iq][ic];
      J_c3 += coordinate_dofs[ic * 3 + 1] * FE4_C1_D01_Q618[0][0][iq][ic];
      J_c1 += coordinate_dofs[ic * 3] * FE4_C1_D01_Q618[0][0][iq][ic];
      J_c2 += coordinate_dofs[ic * 3 + 1] * FE4_C0_D10_Q618[0][0][iq][ic];
      w0 += w[ic] * FE3_C0_Q618[0][0][iq][ic];
      w1 += w[4 + ic] * FE3_C0_Q618[0][0][iq][ic];
    }
    double sv_618[24];
    sv_618[0] = J_c0 * J_c3;
    sv_618[1] = J_c1 * J_c2;
    sv_618[2] = sv_618[0] + -1 * sv_618[1];
    sv_618[3] = J_c0 / sv_618[2];
    sv_618[4] = (-1 * J_c1) / sv_618[2];
    sv_618[5] = sv_618[3] * sv_618[3];
    sv_618[6] = sv_618[3] * sv_618[4];
    sv_618[7] = sv_618[4] * sv_618[4];
    sv_618[8] = J_c3 / sv_618[2];
    sv_618[9] = (-1 * J_c2) / sv_618[2];
    sv_618[10] = sv_618[9] * sv_618[9];
    sv_618[11] = sv_618[8] * sv_618[9];
    sv_618[12] = sv_618[8] * sv_618[8];
    sv_618[13] = sv_618[5] + sv_618[10];
    sv_618[14] = sv_618[6] + sv_618[11];
    sv_618[15] = sv_618[12] + sv_618[7];
    sv_618[16] = (-1 * (-1 + w0)) * w1;
    sv_618[17] = sv_618[13] * (-1 * (1 / pow(sv_618[16], 2)));
    sv_618[18] = sv_618[14] * (-1 * (1 / pow(sv_618[16], 2)));
    sv_618[19] = sv_618[15] * (-1 * (1 / pow(sv_618[16], 2)));
    sv_618[20] = fabs(sv_618[2]);
    sv_618[21] = sv_618[17] * sv_618[20];
    sv_618[22] = sv_618[18] * sv_618[20];
    sv_618[23] = sv_618[19] * sv_618[20];
    const double fw0 = sv_618[23] * weights_618[iq];
    const double fw1 = sv_618[22] * weights_618[iq];
    const double fw2 = sv_618[21] * weights_618[iq];
    double t0[9];
    double t1[9];
    for (int i = 0; i < 9; ++i)
    {
      t0[i] = fw0 * FE8_C0_D10_Q618[0][0][iq][i] + fw1 * FE8_C0_D01_Q618[0][0][iq][i];
      t1[i] = fw1 * FE8_C0_D10_Q618[0][0][iq][i] + fw2 * FE8_C0_D01_Q618[0][0][iq][i];
    }
    for (int i = 0; i < 9; ++i)
      for (int j = 0; j < 9; ++j)
        A[9 * i + j] += FE8_C0_D10_Q618[0][0][iq][j] * t0[i] + FE8_C0_D01_Q618[0][0][iq][j] * t1[i];
  }
}

bool enabled_coefficients_integral_0e9d1cbd6a82dbca0f8b5d515aed78c5bf974453[2] = { false, false };

ufcx_integral integral_0e9d1cbd6a82dbca0f8b5d515aed78c5bf974453 =
{
  .enabled_coefficients = enabled_coefficients_integral_0e9d1cbd6a82dbca0f8b5d515aed78c5bf974453,
  .tabulate_tensor_float64 = tabulate_tensor_integral_0e9d1cbd6a82dbca0f8b5d515aed78c5bf974453,
  .needs_facet_permutations = false,
  .coordinate_element = &element_547176877e4405a4f795e23a410bc677fb590bfe,
};

// End of code for integral integral_0e9d1cbd6a82dbca0f8b5d515aed78c5bf974453

// Code for form form_c79cc5f0f25a1c940a07c450472252e4e63e4107

int original_coefficient_position_form_c79cc5f0f25a1c940a07c450472252e4e63e4107[2] = { 0, 1 };
ufcx_dofmap* dofmaps_form_c79cc5f0f25a1c940a07c450472252e4e63e4107[4] = { &dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d, &dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d, &dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1, &dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1 };
ufcx_finite_element* finite_elements_form_c79cc5f0f25a1c940a07c450472252e4e63e4107[4] = { &element_273bb6edb683274804fdc4c271d881cf56dcbd3d, &element_273bb6edb683274804fdc4c271d881cf56dcbd3d, &element_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1, &element_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1 };

// Return a list of the coefficient names.
const char** coefficient_name_form_c79cc5f0f25a1c940a07c450472252e4e63e4107(void)
{
static const char* names[2] = { "w0", "w1" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_c79cc5f0f25a1c940a07c450472252e4e63e4107(void)
{
return NULL;
}

int* integral_ids_form_c79cc5f0f25a1c940a07c450472252e4e63e4107(ufcx_integral_type integral_type)
{
static int integral_ids_cell_form_c79cc5f0f25a1c940a07c450472252e4e63e4107[1] = { -1 };
switch (integral_type)
{
case cell:
  return integral_ids_cell_form_c79cc5f0f25a1c940a07c450472252e4e63e4107;
default:
  return NULL;
}
}

int num_integrals_form_c79cc5f0f25a1c940a07c450472252e4e63e4107(ufcx_integral_type integral_type)
{
switch (integral_type)
{
case cell:
  return 1;
case interior_facet:
  return 0;
case exterior_facet:
  return 0;
default:
  return 0;
}
}

ufcx_integral** integrals_form_c79cc5f0f25a1c940a07c450472252e4e63e4107(ufcx_integral_type integral_type)
{
static ufcx_integral* integrals_cell_form_c79cc5f0f25a1c940a07c450472252e4e63e4107[1] = { &integral_0e9d1cbd6a82dbca0f8b5d515aed78c5bf974453 };
switch (integral_type)
{
case cell:
  return integrals_cell_form_c79cc5f0f25a1c940a07c450472252e4e63e4107;
default:
  return NULL;
}
}

ufcx_form form_c79cc5f0f25a1c940a07c450472252e4e63e4107 =
{

  .signature = "761d1d1205d6cd2fbd2db6741c7be725a87be80ac859a9e1ba388669d7bd90337790c45e3121ac6812234abf506c4ff11f5531d3c0ff7a737d9b4d39d51d031c",
  .rank = 2,
  .num_coefficients = 2,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_c79cc5f0f25a1c940a07c450472252e4e63e4107,

  .coefficient_name_map = coefficient_name_form_c79cc5f0f25a1c940a07c450472252e4e63e4107,
  .constant_name_map = constant_name_form_c79cc5f0f25a1c940a07c450472252e4e63e4107,

  .finite_elements = finite_elements_form_c79cc5f0f25a1c940a07c450472252e4e63e4107,
  .dofmaps = dofmaps_form_c79cc5f0f25a1c940a07c450472252e4e63e4107,

  .integral_ids = integral_ids_form_c79cc5f0f25a1c940a07c450472252e4e63e4107,
  .num_integrals = num_integrals_form_c79cc5f0f25a1c940a07c450472252e4e63e4107,

  .integrals = integrals_form_c79cc5f0f25a1c940a07c450472252e4e63e4107
};

// Alias name
ufcx_form* form_libffcx_forms_0594a040f6de4bfb4602dd7e8db48129428ea959_0 = &form_c79cc5f0f25a1c940a07c450472252e4e63e4107;

ufcx_function_space* functionspace_form_libffcx_forms_0594a040f6de4bfb4602dd7e8db48129428ea959_0(const char* function_name)
{
static ufcx_function_space functionspace_v_0 =
{
.finite_element = &element_273bb6edb683274804fdc4c271d881cf56dcbd3d,
.dofmap = &dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 4,
.geometry_basix_variant = 1
};
static ufcx_function_space functionspace_v_1 =
{
.finite_element = &element_273bb6edb683274804fdc4c271d881cf56dcbd3d,
.dofmap = &dofmap_273bb6edb683274804fdc4c271d881cf56dcbd3d,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 4,
.geometry_basix_variant = 1
};
static ufcx_function_space functionspace_s⁽⁰⁾ =
{
.finite_element = &element_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1,
.dofmap = &dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 4,
.geometry_basix_variant = 1
};
static ufcx_function_space functionspace_varphi =
{
.finite_element = &element_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1,
.dofmap = &dofmap_e7758b10b4dfcda1cf9cb8cfcc3a7e70760c29c1,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 4,
.geometry_basix_variant = 1
};
if (strcmp(function_name, "v_0") == 0)
  return &functionspace_v_0;
else if (strcmp(function_name, "v_1") == 0)
  return &functionspace_v_1;
else if (strcmp(function_name, "s⁽⁰⁾") == 0)
  return &functionspace_s⁽⁰⁾;
else if (strcmp(function_name, "varphi") == 0)
  return &functionspace_varphi;
return NULL;

}

// End of code for form form_c79cc5f0f25a1c940a07c450472252e4e63e4107


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 59), // char const * *()(void)
/*  1 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION, 44), // int *()(ufcx_integral_type)
/*  3 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // ufcx_integral_type
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION, 45), // int()(ufcx_integral_type)
/*  6 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION, 81), // ufcx_integral * *()(ufcx_integral_type)
/*  9 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/* 12 */ _CFFI_OP(_CFFI_OP_POINTER, 63), // double *
/* 13 */ _CFFI_OP(_CFFI_OP_POINTER, 63), // double const *
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 16 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // int const *
/* 17 */ _CFFI_OP(_CFFI_OP_POINTER, 85), // uint8_t const *
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 19 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *)
/* 20 */ _CFFI_OP(_CFFI_OP_POINTER, 62), // double _Complex *
/* 21 */ _CFFI_OP(_CFFI_OP_POINTER, 62), // double _Complex const *
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 21),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 17),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 65), // float *
/* 29 */ _CFFI_OP(_CFFI_OP_POINTER, 65), // float const *
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 29),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 29),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 17),
/* 34 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *)
/* 36 */ _CFFI_OP(_CFFI_OP_POINTER, 64), // float _Complex *
/* 37 */ _CFFI_OP(_CFFI_OP_POINTER, 64), // float _Complex const *
/* 38 */ _CFFI_OP(_CFFI_OP_NOOP, 37),
/* 39 */ _CFFI_OP(_CFFI_OP_NOOP, 29),
/* 40 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 41 */ _CFFI_OP(_CFFI_OP_NOOP, 17),
/* 42 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 43 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(int *, int, int)
/* 44 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // int *
/* 45 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 46 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 47 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 48 */ _CFFI_OP(_CFFI_OP_FUNCTION, 92), // void()(long double *, long double const *, long double const *, long double const *, int const *, uint8_t const *)
/* 49 */ _CFFI_OP(_CFFI_OP_POINTER, 68), // long double *
/* 50 */ _CFFI_OP(_CFFI_OP_POINTER, 68), // long double const *
/* 51 */ _CFFI_OP(_CFFI_OP_NOOP, 50),
/* 52 */ _CFFI_OP(_CFFI_OP_NOOP, 50),
/* 53 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 54 */ _CFFI_OP(_CFFI_OP_NOOP, 17),
/* 55 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 56 */ _CFFI_OP(_CFFI_OP_POINTER, 57), // _Bool const *
/* 57 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 58 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // char const * *(*)(void)
/* 59 */ _CFFI_OP(_CFFI_OP_POINTER, 60), // char const * *
/* 60 */ _CFFI_OP(_CFFI_OP_POINTER, 61), // char const *
/* 61 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 62 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 49), // double _Complex
/* 63 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 64 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 48), // float _Complex
/* 65 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 66 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // int *(*)(ufcx_integral_type)
/* 67 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // int(*)(ufcx_integral_type)
/* 68 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 15), // long double
/* 69 */ _CFFI_OP(_CFFI_OP_POINTER, 70), // ufcx_basix_custom_finite_element *
/* 70 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_basix_custom_finite_element
/* 71 */ _CFFI_OP(_CFFI_OP_POINTER, 72), // ufcx_dofmap * *
/* 72 */ _CFFI_OP(_CFFI_OP_POINTER, 73), // ufcx_dofmap *
/* 73 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_dofmap
/* 74 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_element_type
/* 75 */ _CFFI_OP(_CFFI_OP_POINTER, 76), // ufcx_finite_element * *
/* 76 */ _CFFI_OP(_CFFI_OP_POINTER, 77), // ufcx_finite_element *
/* 77 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // ufcx_finite_element
/* 78 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // ufcx_form
/* 79 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // ufcx_function_space
/* 80 */ _CFFI_OP(_CFFI_OP_POINTER, 8), // ufcx_integral * *(*)(ufcx_integral_type)
/* 81 */ _CFFI_OP(_CFFI_OP_POINTER, 82), // ufcx_integral * *
/* 82 */ _CFFI_OP(_CFFI_OP_POINTER, 83), // ufcx_integral *
/* 83 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // ufcx_integral
/* 84 */ _CFFI_OP(_CFFI_OP_ENUM, 2), // ufcx_shape
/* 85 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 86 */ _CFFI_OP(_CFFI_OP_POINTER, 11), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/* 87 */ _CFFI_OP(_CFFI_OP_POINTER, 19), // void(*)(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *)
/* 88 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // void(*)(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 89 */ _CFFI_OP(_CFFI_OP_POINTER, 35), // void(*)(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *)
/* 90 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // void(*)(int *, int, int)
/* 91 */ _CFFI_OP(_CFFI_OP_POINTER, 48), // void(*)(long double *, long double const *, long double const *, long double const *, int const *, uint8_t const *)
/* 92 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_ufcx_basix_element(unsigned long long *o)
{
  int n = (ufcx_basix_element) <= 0;
  *o = (unsigned long long)((ufcx_basix_element) | 0);  /* check that ufcx_basix_element is an integer */
  return n;
}

static int _cffi_const_ufcx_mixed_element(unsigned long long *o)
{
  int n = (ufcx_mixed_element) <= 0;
  *o = (unsigned long long)((ufcx_mixed_element) | 0);  /* check that ufcx_mixed_element is an integer */
  return n;
}

static int _cffi_const_ufcx_quadrature_element(unsigned long long *o)
{
  int n = (ufcx_quadrature_element) <= 0;
  *o = (unsigned long long)((ufcx_quadrature_element) | 0);  /* check that ufcx_quadrature_element is an integer */
  return n;
}

static int _cffi_const_ufcx_basix_custom_element(unsigned long long *o)
{
  int n = (ufcx_basix_custom_element) <= 0;
  *o = (unsigned long long)((ufcx_basix_custom_element) | 0);  /* check that ufcx_basix_custom_element is an integer */
  return n;
}

static int _cffi_const_ufcx_real_element(unsigned long long *o)
{
  int n = (ufcx_real_element) <= 0;
  *o = (unsigned long long)((ufcx_real_element) | 0);  /* check that ufcx_real_element is an integer */
  return n;
}

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

static int _cffi_const_interval(unsigned long long *o)
{
  int n = (interval) <= 0;
  *o = (unsigned long long)((interval) | 0);  /* check that interval is an integer */
  return n;
}

static int _cffi_const_triangle(unsigned long long *o)
{
  int n = (triangle) <= 0;
  *o = (unsigned long long)((triangle) | 0);  /* check that triangle is an integer */
  return n;
}

static int _cffi_const_quadrilateral(unsigned long long *o)
{
  int n = (quadrilateral) <= 0;
  *o = (unsigned long long)((quadrilateral) | 0);  /* check that quadrilateral is an integer */
  return n;
}

static int _cffi_const_tetrahedron(unsigned long long *o)
{
  int n = (tetrahedron) <= 0;
  *o = (unsigned long long)((tetrahedron) | 0);  /* check that tetrahedron is an integer */
  return n;
}

static int _cffi_const_hexahedron(unsigned long long *o)
{
  int n = (hexahedron) <= 0;
  *o = (unsigned long long)((hexahedron) | 0);  /* check that hexahedron is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

static int _cffi_const_prism(unsigned long long *o)
{
  int n = (prism) <= 0;
  *o = (unsigned long long)((prism) | 0);  /* check that prism is an integer */
  return n;
}

static int _cffi_const_pyramid(unsigned long long *o)
{
  int n = (pyramid) <= 0;
  *o = (unsigned long long)((pyramid) | 0);  /* check that pyramid is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_dofmap(ufcx_dofmap *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->num_global_support_dofs) | 0);  /* check that 'ufcx_dofmap.num_global_support_dofs' is an integer */
  (void)((p->num_element_support_dofs) | 0);  /* check that 'ufcx_dofmap.num_element_support_dofs' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufcx_dofmap.block_size' is an integer */
  { int * *tmp = &p->num_entity_dofs; (void)tmp; }
  { void(* *tmp)(int *, int, int) = &p->tabulate_entity_dofs; (void)tmp; }
  { int * *tmp = &p->num_entity_closure_dofs; (void)tmp; }
  { void(* *tmp)(int *, int, int) = &p->tabulate_entity_closure_dofs; (void)tmp; }
  (void)((p->num_sub_dofmaps) | 0);  /* check that 'ufcx_dofmap.num_sub_dofmaps' is an integer */
  { ufcx_dofmap * * *tmp = &p->sub_dofmaps; (void)tmp; }
}
struct _cffi_align__ufcx_dofmap { char x; ufcx_dofmap y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_finite_element(ufcx_finite_element *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  { ufcx_shape *tmp = &p->cell_shape; (void)tmp; }
  { ufcx_element_type *tmp = &p->element_type; (void)tmp; }
  (void)((p->topological_dimension) | 0);  /* check that 'ufcx_finite_element.topological_dimension' is an integer */
  (void)((p->geometric_dimension) | 0);  /* check that 'ufcx_finite_element.geometric_dimension' is an integer */
  (void)((p->space_dimension) | 0);  /* check that 'ufcx_finite_element.space_dimension' is an integer */
  (void)((p->value_rank) | 0);  /* check that 'ufcx_finite_element.value_rank' is an integer */
  { int * *tmp = &p->value_shape; (void)tmp; }
  (void)((p->value_size) | 0);  /* check that 'ufcx_finite_element.value_size' is an integer */
  (void)((p->reference_value_rank) | 0);  /* check that 'ufcx_finite_element.reference_value_rank' is an integer */
  { int * *tmp = &p->reference_value_shape; (void)tmp; }
  (void)((p->reference_value_size) | 0);  /* check that 'ufcx_finite_element.reference_value_size' is an integer */
  (void)((p->degree) | 0);  /* check that 'ufcx_finite_element.degree' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufcx_finite_element.block_size' is an integer */
  { char const * *tmp = &p->family; (void)tmp; }
  (void)((p->basix_family) | 0);  /* check that 'ufcx_finite_element.basix_family' is an integer */
  (void)((p->basix_cell) | 0);  /* check that 'ufcx_finite_element.basix_cell' is an integer */
  (void)((p->discontinuous) | 0);  /* check that 'ufcx_finite_element.discontinuous' is an integer */
  (void)((p->lagrange_variant) | 0);  /* check that 'ufcx_finite_element.lagrange_variant' is an integer */
  (void)((p->dpc_variant) | 0);  /* check that 'ufcx_finite_element.dpc_variant' is an integer */
  (void)((p->num_sub_elements) | 0);  /* check that 'ufcx_finite_element.num_sub_elements' is an integer */
  { ufcx_finite_element * * *tmp = &p->sub_elements; (void)tmp; }
  { ufcx_basix_custom_finite_element * *tmp = &p->custom_element; (void)tmp; }
}
struct _cffi_align__ufcx_finite_element { char x; ufcx_finite_element y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_form(ufcx_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufcx_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufcx_form.num_coefficients' is an integer */
  (void)((p->num_constants) | 0);  /* check that 'ufcx_form.num_constants' is an integer */
  { int * *tmp = &p->original_coefficient_position; (void)tmp; }
  { char const * *(* *tmp)(void) = &p->coefficient_name_map; (void)tmp; }
  { char const * *(* *tmp)(void) = &p->constant_name_map; (void)tmp; }
  { ufcx_finite_element * * *tmp = &p->finite_elements; (void)tmp; }
  { ufcx_dofmap * * *tmp = &p->dofmaps; (void)tmp; }
  { int *(* *tmp)(ufcx_integral_type) = &p->integral_ids; (void)tmp; }
  { int(* *tmp)(ufcx_integral_type) = &p->num_integrals; (void)tmp; }
  { ufcx_integral * *(* *tmp)(ufcx_integral_type) = &p->integrals; (void)tmp; }
}
struct _cffi_align__ufcx_form { char x; ufcx_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_integral(ufcx_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(float *, float const *, float const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_float32; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_float64; (void)tmp; }
  { void(* *tmp)(long double *, long double const *, long double const *, long double const *, int const *, uint8_t const *) = &p->tabulate_tensor_longdouble; (void)tmp; }
  { void(* *tmp)(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex64; (void)tmp; }
  { void(* *tmp)(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex128; (void)tmp; }
  (void)((p->needs_facet_permutations) | 0);  /* check that 'ufcx_integral.needs_facet_permutations' is an integer */
  { ufcx_finite_element * *tmp = &p->coordinate_element; (void)tmp; }
}
struct _cffi_align__ufcx_integral { char x; ufcx_integral y; };

static ufcx_form *_cffi_var_form_c79cc5f0f25a1c940a07c450472252e4e63e4107(void)
{
  return &(form_c79cc5f0f25a1c940a07c450472252e4e63e4107);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_c79cc5f0f25a1c940a07c450472252e4e63e4107", (void *)_cffi_var_form_c79cc5f0f25a1c940a07c450472252e4e63e4107, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 78), (void *)0 },
  { "hexahedron", (void *)_cffi_const_hexahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interval", (void *)_cffi_const_interval, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "prism", (void *)_cffi_const_prism, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "pyramid", (void *)_cffi_const_pyramid, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "quadrilateral", (void *)_cffi_const_quadrilateral, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "tetrahedron", (void *)_cffi_const_tetrahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "triangle", (void *)_cffi_const_triangle, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_basix_custom_element", (void *)_cffi_const_ufcx_basix_custom_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_basix_element", (void *)_cffi_const_ufcx_basix_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_mixed_element", (void *)_cffi_const_ufcx_mixed_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_quadrature_element", (void *)_cffi_const_ufcx_quadrature_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_real_element", (void *)_cffi_const_ufcx_real_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_dofmap, signature),
                 sizeof(((ufcx_dofmap *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "num_global_support_dofs", offsetof(ufcx_dofmap, num_global_support_dofs),
                               sizeof(((ufcx_dofmap *)0)->num_global_support_dofs),
                               _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_element_support_dofs", offsetof(ufcx_dofmap, num_element_support_dofs),
                                sizeof(((ufcx_dofmap *)0)->num_element_support_dofs),
                                _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "block_size", offsetof(ufcx_dofmap, block_size),
                  sizeof(((ufcx_dofmap *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_entity_dofs", offsetof(ufcx_dofmap, num_entity_dofs),
                       sizeof(((ufcx_dofmap *)0)->num_entity_dofs),
                       _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "tabulate_entity_dofs", offsetof(ufcx_dofmap, tabulate_entity_dofs),
                            sizeof(((ufcx_dofmap *)0)->tabulate_entity_dofs),
                            _CFFI_OP(_CFFI_OP_NOOP, 90) },
  { "num_entity_closure_dofs", offsetof(ufcx_dofmap, num_entity_closure_dofs),
                               sizeof(((ufcx_dofmap *)0)->num_entity_closure_dofs),
                               _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "tabulate_entity_closure_dofs", offsetof(ufcx_dofmap, tabulate_entity_closure_dofs),
                                    sizeof(((ufcx_dofmap *)0)->tabulate_entity_closure_dofs),
                                    _CFFI_OP(_CFFI_OP_NOOP, 90) },
  { "num_sub_dofmaps", offsetof(ufcx_dofmap, num_sub_dofmaps),
                       sizeof(((ufcx_dofmap *)0)->num_sub_dofmaps),
                       _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "sub_dofmaps", offsetof(ufcx_dofmap, sub_dofmaps),
                   sizeof(((ufcx_dofmap *)0)->sub_dofmaps),
                   _CFFI_OP(_CFFI_OP_NOOP, 71) },
  { "signature", offsetof(ufcx_finite_element, signature),
                 sizeof(((ufcx_finite_element *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "cell_shape", offsetof(ufcx_finite_element, cell_shape),
                  sizeof(((ufcx_finite_element *)0)->cell_shape),
                  _CFFI_OP(_CFFI_OP_NOOP, 84) },
  { "element_type", offsetof(ufcx_finite_element, element_type),
                    sizeof(((ufcx_finite_element *)0)->element_type),
                    _CFFI_OP(_CFFI_OP_NOOP, 74) },
  { "topological_dimension", offsetof(ufcx_finite_element, topological_dimension),
                             sizeof(((ufcx_finite_element *)0)->topological_dimension),
                             _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "geometric_dimension", offsetof(ufcx_finite_element, geometric_dimension),
                           sizeof(((ufcx_finite_element *)0)->geometric_dimension),
                           _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "space_dimension", offsetof(ufcx_finite_element, space_dimension),
                       sizeof(((ufcx_finite_element *)0)->space_dimension),
                       _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "value_rank", offsetof(ufcx_finite_element, value_rank),
                  sizeof(((ufcx_finite_element *)0)->value_rank),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "value_shape", offsetof(ufcx_finite_element, value_shape),
                   sizeof(((ufcx_finite_element *)0)->value_shape),
                   _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "value_size", offsetof(ufcx_finite_element, value_size),
                  sizeof(((ufcx_finite_element *)0)->value_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "reference_value_rank", offsetof(ufcx_finite_element, reference_value_rank),
                            sizeof(((ufcx_finite_element *)0)->reference_value_rank),
                            _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "reference_value_shape", offsetof(ufcx_finite_element, reference_value_shape),
                             sizeof(((ufcx_finite_element *)0)->reference_value_shape),
                             _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "reference_value_size", offsetof(ufcx_finite_element, reference_value_size),
                            sizeof(((ufcx_finite_element *)0)->reference_value_size),
                            _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "degree", offsetof(ufcx_finite_element, degree),
              sizeof(((ufcx_finite_element *)0)->degree),
              _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "block_size", offsetof(ufcx_finite_element, block_size),
                  sizeof(((ufcx_finite_element *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "family", offsetof(ufcx_finite_element, family),
              sizeof(((ufcx_finite_element *)0)->family),
              _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "basix_family", offsetof(ufcx_finite_element, basix_family),
                    sizeof(((ufcx_finite_element *)0)->basix_family),
                    _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "basix_cell", offsetof(ufcx_finite_element, basix_cell),
                  sizeof(((ufcx_finite_element *)0)->basix_cell),
                  _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "discontinuous", offsetof(ufcx_finite_element, discontinuous),
                     sizeof(((ufcx_finite_element *)0)->discontinuous),
                     _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "lagrange_variant", offsetof(ufcx_finite_element, lagrange_variant),
                        sizeof(((ufcx_finite_element *)0)->lagrange_variant),
                        _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "dpc_variant", offsetof(ufcx_finite_element, dpc_variant),
                   sizeof(((ufcx_finite_element *)0)->dpc_variant),
                   _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_sub_elements", offsetof(ufcx_finite_element, num_sub_elements),
                        sizeof(((ufcx_finite_element *)0)->num_sub_elements),
                        _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "sub_elements", offsetof(ufcx_finite_element, sub_elements),
                    sizeof(((ufcx_finite_element *)0)->sub_elements),
                    _CFFI_OP(_CFFI_OP_NOOP, 75) },
  { "custom_element", offsetof(ufcx_finite_element, custom_element),
                      sizeof(((ufcx_finite_element *)0)->custom_element),
                      _CFFI_OP(_CFFI_OP_NOOP, 69) },
  { "signature", offsetof(ufcx_form, signature),
                 sizeof(((ufcx_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "rank", offsetof(ufcx_form, rank),
            sizeof(((ufcx_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_coefficients", offsetof(ufcx_form, num_coefficients),
                        sizeof(((ufcx_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "num_constants", offsetof(ufcx_form, num_constants),
                     sizeof(((ufcx_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "original_coefficient_position", offsetof(ufcx_form, original_coefficient_position),
                                     sizeof(((ufcx_form *)0)->original_coefficient_position),
                                     _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "coefficient_name_map", offsetof(ufcx_form, coefficient_name_map),
                            sizeof(((ufcx_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "constant_name_map", offsetof(ufcx_form, constant_name_map),
                         sizeof(((ufcx_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "finite_elements", offsetof(ufcx_form, finite_elements),
                       sizeof(((ufcx_form *)0)->finite_elements),
                       _CFFI_OP(_CFFI_OP_NOOP, 75) },
  { "dofmaps", offsetof(ufcx_form, dofmaps),
               sizeof(((ufcx_form *)0)->dofmaps),
               _CFFI_OP(_CFFI_OP_NOOP, 71) },
  { "integral_ids", offsetof(ufcx_form, integral_ids),
                    sizeof(((ufcx_form *)0)->integral_ids),
                    _CFFI_OP(_CFFI_OP_NOOP, 66) },
  { "num_integrals", offsetof(ufcx_form, num_integrals),
                     sizeof(((ufcx_form *)0)->num_integrals),
                     _CFFI_OP(_CFFI_OP_NOOP, 67) },
  { "integrals", offsetof(ufcx_form, integrals),
                 sizeof(((ufcx_form *)0)->integrals),
                 _CFFI_OP(_CFFI_OP_NOOP, 80) },
  { "enabled_coefficients", offsetof(ufcx_integral, enabled_coefficients),
                            sizeof(((ufcx_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "tabulate_tensor_float32", offsetof(ufcx_integral, tabulate_tensor_float32),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float32),
                               _CFFI_OP(_CFFI_OP_NOOP, 88) },
  { "tabulate_tensor_float64", offsetof(ufcx_integral, tabulate_tensor_float64),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float64),
                               _CFFI_OP(_CFFI_OP_NOOP, 86) },
  { "tabulate_tensor_longdouble", offsetof(ufcx_integral, tabulate_tensor_longdouble),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_longdouble),
                                  _CFFI_OP(_CFFI_OP_NOOP, 91) },
  { "tabulate_tensor_complex64", offsetof(ufcx_integral, tabulate_tensor_complex64),
                                 sizeof(((ufcx_integral *)0)->tabulate_tensor_complex64),
                                 _CFFI_OP(_CFFI_OP_NOOP, 89) },
  { "tabulate_tensor_complex128", offsetof(ufcx_integral, tabulate_tensor_complex128),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_complex128),
                                  _CFFI_OP(_CFFI_OP_NOOP, 87) },
  { "needs_facet_permutations", offsetof(ufcx_integral, needs_facet_permutations),
                                sizeof(((ufcx_integral *)0)->needs_facet_permutations),
                                _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "coordinate_element", offsetof(ufcx_integral, coordinate_element),
                          sizeof(((ufcx_integral *)0)->coordinate_element),
                          _CFFI_OP(_CFFI_OP_NOOP, 76) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_basix_custom_finite_element", 70, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ufcx_dofmap", 73, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_dofmap), offsetof(struct _cffi_align__ufcx_dofmap, y), 0, 10 },
  { "ufcx_finite_element", 77, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_finite_element), offsetof(struct _cffi_align__ufcx_finite_element, y), 10, 23 },
  { "ufcx_form", 78, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_form), offsetof(struct _cffi_align__ufcx_form, y), 33, 12 },
  { "ufcx_function_space", 79, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ufcx_integral", 83, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_integral), offsetof(struct _cffi_align__ufcx_integral, y), 45, 8 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_element_type", 74, _cffi_prim_int(sizeof(ufcx_element_type), ((ufcx_element_type)-1) <= 0),
    "ufcx_basix_element,ufcx_mixed_element,ufcx_quadrature_element,ufcx_basix_custom_element,ufcx_real_element" },
  { "$ufcx_integral_type", 3, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet" },
  { "$ufcx_shape", 84, _cffi_prim_int(sizeof(ufcx_shape), ((ufcx_shape)-1) <= 0),
    "interval,triangle,quadrilateral,tetrahedron,hexahedron,vertex,prism,pyramid" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_basix_custom_finite_element", 70 },
  { "ufcx_dofmap", 73 },
  { "ufcx_element_type", 74 },
  { "ufcx_finite_element", 77 },
  { "ufcx_form", 78 },
  { "ufcx_function_space", 79 },
  { "ufcx_integral", 83 },
  { "ufcx_integral_type", 3 },
  { "ufcx_shape", 84 },
  { "ufcx_tabulate_tensor_complex128", 19 },
  { "ufcx_tabulate_tensor_complex64", 35 },
  { "ufcx_tabulate_tensor_float32", 27 },
  { "ufcx_tabulate_tensor_float64", 11 },
  { "ufcx_tabulate_tensor_longdouble", 48 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  17,  /* num_globals */
  6,  /* num_struct_unions */
  3,  /* num_enums */
  14,  /* num_typenames */
  NULL,  /* no includes */
  93,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_0594a040f6de4bfb4602dd7e8db48129428ea959(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffcx_forms_0594a040f6de4bfb4602dd7e8db48129428ea959(void) { return NULL; }
#  else
     initlibffcx_forms_0594a040f6de4bfb4602dd7e8db48129428ea959(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffcx_forms_0594a040f6de4bfb4602dd7e8db48129428ea959(void)
{
  return _cffi_init("libffcx_forms_0594a040f6de4bfb4602dd7e8db48129428ea959", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffcx_forms_0594a040f6de4bfb4602dd7e8db48129428ea959(void)
{
  _cffi_init("libffcx_forms_0594a040f6de4bfb4602dd7e8db48129428ea959", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
